version: '3.8'
services:
  movies:
    image: kumar2622/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: kumar2622/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: kumar2622/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: kumar2622/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

